### ISSUE TITLE
Accumulator array length

### ISSUE THREAD

**Issue by siamezzze** [boechat107/imgproc_scripts#2]
Hello and thanks for sharing the code!
I'm trying to run your implementation of the Hough transform for ellipces in order to compare it with mine.
While it seems quick and efficient on some exampes, I keep bumping into the same error while trying to run it on others:

> octave:7> par = hough_ellipse(img)
> error: hough_ellipse: A(I): index out of bounds; value 515 out of bound 512
> error: called from:
> error:   /home/siamezzze/Projects/Hough/boechat107/imgproc_scripts/hough_ellipse.m at line 84,
> column 31

I'm not familiar with Matlab/Octave, but seems like accumulator array is too small.

Attaching the sample image.
![s_1_1](https://cloud.githubusercontent.com/assets/2546381/8319372/c6985b42-1a16-11e5-8a99-157670d4f8bf.jpg)

**Comment by boechat107** [comment]
Hello, @siamezzze!

Thank you very much for your comments and tests. You had really found a bug!  =)

I fixed the code and added some comments (both on code and on the commit message). I hope the explanation is clear enough and that the algorithm now works for you.

If you find any other problem, don't hesitate to tell me.
